/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.request


import com.google.gson.annotations.SerializedName

/**
 * 管理员发布消息请求
 *
 * @param type 消息类型：SYSTEM (全员系统消息), ALERT (定向预警消息)
 * @param title 消息标题
 * @param content 消息内容
 * @param targetCrops 定向作物偏好 (仅ALERT类型有效，不填则发给所有地区匹配的用户)
 * @param targetLocation 定向地理位置 (仅ALERT类型有效，不填则发给所有作物匹配的用户)
 */


data class AdminMessageCreateRequest (

    /* 消息类型：SYSTEM (全员系统消息), ALERT (定向预警消息) */
    @SerializedName("type")
    val type: kotlin.String,

    /* 消息标题 */
    @SerializedName("title")
    val title: kotlin.String,

    /* 消息内容 */
    @SerializedName("content")
    val content: kotlin.String,

    /* 定向作物偏好 (仅ALERT类型有效，不填则发给所有地区匹配的用户) */
    @SerializedName("targetCrops")
    val targetCrops: kotlin.collections.List<kotlin.String>? = null,

    /* 定向地理位置 (仅ALERT类型有效，不填则发给所有作物匹配的用户) */
    @SerializedName("targetLocation")
    val targetLocation: kotlin.String? = null

)

