/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.request


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param text 
 * @param imageUrl 
 */


data class ChatRequest (

    @SerializedName("text")
    val text: kotlin.String? = null,

    @SerializedName("imageUrl")
    val imageUrl: kotlin.String? = null

)

