/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.request


import com.google.gson.annotations.SerializedName

/**
 * Agent 诊断请求参数
 *
 * @param text 用户的提问文本
 * @param imageUrl 图片的 Base64 字符串或公开的 HTTP URL
 * @param useSingleModel 指定是否使用单模型方案（传给底层的多模态消息），默认为系统配置
 * @param extraInfo 预留的额外信息，如客户端的预处理结果，会一并提交给大模型作为上下文参考
 */


data class ChatRequest (

    /* 用户的提问文本 */
    @SerializedName("text")
    val text: kotlin.String? = null,

    /* 图片的 Base64 字符串或公开的 HTTP URL */
    @SerializedName("imageUrl")
    val imageUrl: kotlin.String? = null,

    /* 指定是否使用单模型方案（传给底层的多模态消息），默认为系统配置 */
    @SerializedName("useSingleModel")
    val useSingleModel: kotlin.Boolean? = null,

    /* 预留的额外信息，如客户端的预处理结果，会一并提交给大模型作为上下文参考 */
    @SerializedName("extraInfo")
    val extraInfo: kotlin.String? = null

)

