/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.request


import com.google.gson.annotations.SerializedName

/**
 * 初始化分片上传请求
 *
 * @param fileHash 文件的唯一Hash值（如MD5/SHA256），用于标识文件和断点续传
 * @param filename 原始文件名
 * @param partCount 分片总数
 * @param contentType 文件的ContentType，不传则自动推断
 */


data class MultipartUploadInitRequest (

    /* 文件的唯一Hash值（如MD5/SHA256），用于标识文件和断点续传 */
    @SerializedName("fileHash")
    val fileHash: kotlin.String,

    /* 原始文件名 */
    @SerializedName("filename")
    val filename: kotlin.String,

    /* 分片总数 */
    @SerializedName("partCount")
    val partCount: kotlin.Int,

    /* 文件的ContentType，不传则自动推断 */
    @SerializedName("contentType")
    val contentType: kotlin.String? = null

)

