/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.request


import com.google.gson.annotations.SerializedName

/**
 * 完成分片上传合并请求
 *
 * @param uploadId 上传任务ID
 * @param filename 原始文件名
 * @param partCount 分片总数
 * @param contentType 文件的ContentType
 * @param prefix 上传路径前缀
 */


data class MultipartUploadCompleteRequest (

    /* 上传任务ID */
    @SerializedName("uploadId")
    val uploadId: kotlin.String,

    /* 原始文件名 */
    @SerializedName("filename")
    val filename: kotlin.String,

    /* 分片总数 */
    @SerializedName("partCount")
    val partCount: kotlin.Int,

    /* 文件的ContentType */
    @SerializedName("contentType")
    val contentType: kotlin.String? = null,

    /* 上传路径前缀 */
    @SerializedName("prefix")
    val prefix: kotlin.String? = null

)

