/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.request


import com.google.gson.annotations.SerializedName

/**
 * 创建作物请求
 *
 * @param plantName 植物名称
 * @param imageUrl 植物图片URL
 * @param status 植物状态
 * @param plantingDate 种植时间
 * @param maturityDate 预计成熟时间
 * @param pestCount 病虫害次数
 */


data class MyCropCreateRequest (

    /* 植物名称 */
    @SerializedName("plantName")
    val plantName: kotlin.String? = null,

    /* 植物图片URL */
    @SerializedName("imageUrl")
    val imageUrl: kotlin.String? = null,

    /* 植物状态 */
    @SerializedName("status")
    val status: kotlin.String? = null,

    /* 种植时间 */
    @SerializedName("plantingDate")
    val plantingDate: java.time.LocalDate? = null,

    /* 预计成熟时间 */
    @SerializedName("maturityDate")
    val maturityDate: java.time.LocalDate? = null,

    /* 病虫害次数 */
    @SerializedName("pestCount")
    val pestCount: kotlin.Int? = null

)

