/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.request


import com.google.gson.annotations.SerializedName

/**
 * 发布新帖子请求参数
 *
 * @param title 帖子标题
 * @param content 帖子内容
 * @param images 帖子图片列表
 * @param tags 关联的农作物标签列表
 */


data class PostCreateRequest (

    /* 帖子标题 */
    @SerializedName("title")
    val title: kotlin.String,

    /* 帖子内容 */
    @SerializedName("content")
    val content: kotlin.String,

    /* 帖子图片列表 */
    @SerializedName("images")
    val images: kotlin.collections.List<kotlin.String>? = null,

    /* 关联的农作物标签列表 */
    @SerializedName("tags")
    val tags: kotlin.collections.List<kotlin.String>? = null

)

