/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.request


import com.google.gson.annotations.SerializedName

/**
 * 个人资料更新请求，字段为空则不更新
 *
 * @param fullName 全名
 * @param avatarUrl 头像URL
 * @param bio 个人简介
 * @param location 地理位置
 * @param followedCrops 关注的农作物（逗号分隔）
 */


data class ProfileUpdateRequest (

    /* 全名 */
    @SerializedName("fullName")
    val fullName: kotlin.String? = null,

    /* 头像URL */
    @SerializedName("avatarUrl")
    val avatarUrl: kotlin.String? = null,

    /* 个人简介 */
    @SerializedName("bio")
    val bio: kotlin.String? = null,

    /* 地理位置 */
    @SerializedName("location")
    val location: kotlin.String? = null,

    /* 关注的农作物（逗号分隔） */
    @SerializedName("followedCrops")
    val followedCrops: kotlin.String? = null

)

