/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.request


import com.google.gson.annotations.SerializedName

/**
 * 刷新Token请求参数
 *
 * @param refreshToken Refresh Token
 */


data class RefreshTokenRequest (

    /* Refresh Token */
    @SerializedName("refreshToken")
    val refreshToken: kotlin.String

)

