/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.request


import com.google.gson.annotations.SerializedName

/**
 * 发送短信验证码请求
 *
 * @param phone 接收验证码的手机号
 */


data class SendSmsRequest (

    /* 接收验证码的手机号 */
    @SerializedName("phone")
    val phone: kotlin.String

)

