/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.request


import com.google.gson.annotations.SerializedName

/**
 * 标签操作请求 (增加或取消标签)
 *
 * @param recordDate 打卡日期
 * @param tagType 标签类型: WATERING, FERTILIZING, MEDICATION, NOTE
 * @param content 笔记内容 (仅在 tagType 为 NOTE 时有效)
 */


data class TagOperationRequest (

    /* 打卡日期 */
    @SerializedName("recordDate")
    val recordDate: java.time.LocalDate? = null,

    /* 标签类型: WATERING, FERTILIZING, MEDICATION, NOTE */
    @SerializedName("tagType")
    val tagType: kotlin.String? = null,

    /* 笔记内容 (仅在 tagType 为 NOTE 时有效) */
    @SerializedName("content")
    val content: kotlin.String? = null

)

