/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.response


import com.google.gson.annotations.SerializedName

/**
 * 数据列表
 *
 * @param id 
 * @param type 
 * @param title 
 * @param content 
 * @param targetLocation 
 * @param targetCrops 
 * @param createdAt 
 */


data class AdminMessage (

    @SerializedName("id")
    val id: kotlin.Long? = null,

    @SerializedName("type")
    val type: kotlin.String? = null,

    @SerializedName("title")
    val title: kotlin.String? = null,

    @SerializedName("content")
    val content: kotlin.String? = null,

    @SerializedName("targetLocation")
    val targetLocation: kotlin.String? = null,

    @SerializedName("targetCrops")
    val targetCrops: kotlin.String? = null,

    @SerializedName("createdAt")
    val createdAt: java.time.OffsetDateTime? = null

)

