/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.response


import com.google.gson.annotations.SerializedName

/**
 * 管理员更新用户请求参数
 *
 * @param username 用户名
 * @param phone 手机号
 * @param role 角色 (USER / ADMIN)
 * @param fullName 全名
 * @param avatarUrl 头像URL
 * @param bio 个人简介
 * @param location 地理位置
 * @param followedCrops 关注的农作物列表
 */


data class AdminUserUpdateDto (

    /* 用户名 */
    @SerializedName("username")
    val username: kotlin.String? = null,

    /* 手机号 */
    @SerializedName("phone")
    val phone: kotlin.String? = null,

    /* 角色 (USER / ADMIN) */
    @SerializedName("role")
    val role: kotlin.String? = null,

    /* 全名 */
    @SerializedName("fullName")
    val fullName: kotlin.String? = null,

    /* 头像URL */
    @SerializedName("avatarUrl")
    val avatarUrl: kotlin.String? = null,

    /* 个人简介 */
    @SerializedName("bio")
    val bio: kotlin.String? = null,

    /* 地理位置 */
    @SerializedName("location")
    val location: kotlin.String? = null,

    /* 关注的农作物列表 */
    @SerializedName("followedCrops")
    val followedCrops: kotlin.collections.List<kotlin.String>? = null

)

