/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.response


import com.google.gson.annotations.SerializedName

/**
 * Agent 识别历史记录实体
 *
 * @param id 主键ID
 * @param userId 用户ID
 * @param userQuery 用户提问文本
 * @param imageUrl 图片地址或Base64(截断)
 * @param imageWidth 图片宽度（像素）
 * @param imageHeight 图片高度（像素）
 * @param agentResponse Agent返回的诊断结果
 * @param createTime 创建时间
 */


data class AgentChatHistory (

    /* 主键ID */
    @SerializedName("id")
    val id: kotlin.Long? = null,

    /* 用户ID */
    @SerializedName("userId")
    val userId: kotlin.Long? = null,

    /* 用户提问文本 */
    @SerializedName("userQuery")
    val userQuery: kotlin.String? = null,

    /* 图片地址或Base64(截断) */
    @SerializedName("imageUrl")
    val imageUrl: kotlin.String? = null,

    /* 图片宽度（像素） */
    @SerializedName("imageWidth")
    val imageWidth: kotlin.Int? = null,

    /* 图片高度（像素） */
    @SerializedName("imageHeight")
    val imageHeight: kotlin.Int? = null,

    /* Agent返回的诊断结果 */
    @SerializedName("agentResponse")
    val agentResponse: kotlin.String? = null,

    /* 创建时间 */
    @SerializedName("createTime")
    val createTime: java.time.OffsetDateTime? = null

)

