/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.response

import com.agri.pest.client.model.response.Profile

import com.google.gson.annotations.SerializedName

/**
 * Agent 诊断响应(带耗时剖析)
 *
 * @param answer 模型回答文本
 * @param profile 
 */


data class ChatProfileResponse (

    /* 模型回答文本 */
    @SerializedName("answer")
    val answer: kotlin.String? = null,

    @SerializedName("profile")
    val profile: Profile? = null

)

