/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.response


import com.google.gson.annotations.SerializedName

/**
 * 评论信息响应结果
 *
 * @param id 评论ID
 * @param postId 帖子ID
 * @param content 内容
 * @param authorId 作者ID
 * @param authorName 作者用户名
 * @param authorAvatar 作者头像
 * @param createdAt 创建时间
 */


data class CommentResponseDto (

    /* 评论ID */
    @SerializedName("id")
    val id: kotlin.Long? = null,

    /* 帖子ID */
    @SerializedName("postId")
    val postId: kotlin.Long? = null,

    /* 内容 */
    @SerializedName("content")
    val content: kotlin.String? = null,

    /* 作者ID */
    @SerializedName("authorId")
    val authorId: kotlin.Long? = null,

    /* 作者用户名 */
    @SerializedName("authorName")
    val authorName: kotlin.String? = null,

    /* 作者头像 */
    @SerializedName("authorAvatar")
    val authorAvatar: kotlin.String? = null,

    /* 创建时间 */
    @SerializedName("createdAt")
    val createdAt: java.time.OffsetDateTime? = null

)

