/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.response


import com.google.gson.annotations.SerializedName

/**
 * 种植记录/标签信息
 *
 * @param id 记录ID
 * @param recordDate 打卡日期
 * @param tagType 标签类型: WATERING(浇水), FERTILIZING(施肥), MEDICATION(用药), NOTE(笔记)
 * @param content 笔记内容或状态文案
 * @param status 状态: 0-待处理, 1-已完成
 */


data class CultivationRecordDto (

    /* 记录ID */
    @SerializedName("id")
    val id: kotlin.Long? = null,

    /* 打卡日期 */
    @SerializedName("recordDate")
    val recordDate: java.time.LocalDate? = null,

    /* 标签类型: WATERING(浇水), FERTILIZING(施肥), MEDICATION(用药), NOTE(笔记) */
    @SerializedName("tagType")
    val tagType: kotlin.String? = null,

    /* 笔记内容或状态文案 */
    @SerializedName("content")
    val content: kotlin.String? = null,

    /* 状态: 0-待处理, 1-已完成 */
    @SerializedName("status")
    val status: kotlin.Int? = null

)

