/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.response


import com.google.gson.annotations.SerializedName

/**
 * 结构化诊断结果
 *
 * @param diseaseName 病害名称
 * @param controlPlan 防治方案
 */


data class DiagnosisItem (

    /* 病害名称 */
    @SerializedName("diseaseName")
    val diseaseName: kotlin.String? = null,

    /* 防治方案 */
    @SerializedName("controlPlan")
    val controlPlan: kotlin.String? = null

)

