/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.response


import com.google.gson.annotations.SerializedName

/**
 * 图片尺寸信息
 *
 * @param width 图片宽度（像素）
 * @param height 图片高度（像素）
 */


data class ImageSizeDto (

    /* 图片宽度（像素） */
    @SerializedName("width")
    val width: kotlin.Int? = null,

    /* 图片高度（像素） */
    @SerializedName("height")
    val height: kotlin.Int? = null

)

