/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.response

import com.agri.pest.client.model.response.PageResultMessageResponseDto

import com.google.gson.annotations.SerializedName

/**
 * 分组消息列表响应
 *
 * @param systemMessages 
 * @param systemUnreadCount 系统消息未读数
 * @param alertMessages 
 * @param alertUnreadCount 预警消息未读数
 * @param commentMessages 
 * @param commentUnreadCount 评论消息未读数
 */


data class MessageGroupResponseDto (

    @SerializedName("systemMessages")
    val systemMessages: PageResultMessageResponseDto? = null,

    /* 系统消息未读数 */
    @SerializedName("systemUnreadCount")
    val systemUnreadCount: kotlin.Long? = null,

    @SerializedName("alertMessages")
    val alertMessages: PageResultMessageResponseDto? = null,

    /* 预警消息未读数 */
    @SerializedName("alertUnreadCount")
    val alertUnreadCount: kotlin.Long? = null,

    @SerializedName("commentMessages")
    val commentMessages: PageResultMessageResponseDto? = null,

    /* 评论消息未读数 */
    @SerializedName("commentUnreadCount")
    val commentUnreadCount: kotlin.Long? = null

)

