/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.response


import com.google.gson.annotations.SerializedName

/**
 * 消息通知响应对象
 *
 * @param id 消息ID
 * @param type 消息类型：LIKE (点赞), COMMENT (评论), SYSTEM (系统), ALERT (预警)
 * @param title 消息标题
 * @param content 消息内容
 * @param senderId 发送者ID (系统消息或预警消息时可能为空)
 * @param senderName 发送者用户名
 * @param senderAvatar 发送者头像
 * @param postId 关联的帖子ID
 * @param isRead 是否已读
 * @param createdAt 接收时间
 */


data class MessageResponseDto (

    /* 消息ID */
    @SerializedName("id")
    val id: kotlin.Long? = null,

    /* 消息类型：LIKE (点赞), COMMENT (评论), SYSTEM (系统), ALERT (预警) */
    @SerializedName("type")
    val type: kotlin.String? = null,

    /* 消息标题 */
    @SerializedName("title")
    val title: kotlin.String? = null,

    /* 消息内容 */
    @SerializedName("content")
    val content: kotlin.String? = null,

    /* 发送者ID (系统消息或预警消息时可能为空) */
    @SerializedName("senderId")
    val senderId: kotlin.Long? = null,

    /* 发送者用户名 */
    @SerializedName("senderName")
    val senderName: kotlin.String? = null,

    /* 发送者头像 */
    @SerializedName("senderAvatar")
    val senderAvatar: kotlin.String? = null,

    /* 关联的帖子ID */
    @SerializedName("postId")
    val postId: kotlin.Long? = null,

    /* 是否已读 */
    @SerializedName("isRead")
    val isRead: kotlin.Boolean? = null,

    /* 接收时间 */
    @SerializedName("createdAt")
    val createdAt: java.time.OffsetDateTime? = null

)

