/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.response


import com.google.gson.annotations.SerializedName

/**
 * 初始化分片上传响应
 *
 * @param uploadId 上传任务ID，后续合并和上传需要用到（当前实现为fileHash）
 * @param uploadedParts 已经上传成功的分片序号列表（断点续传用，从1开始）
 * @param uploadUrls 需要上传的分片对应的预签名URL字典（Key为分片序号，Value为PUT请求的URL）
 */


data class MultipartUploadInitResponse (

    /* 上传任务ID，后续合并和上传需要用到（当前实现为fileHash） */
    @SerializedName("uploadId")
    val uploadId: kotlin.String? = null,

    /* 已经上传成功的分片序号列表（断点续传用，从1开始） */
    @SerializedName("uploadedParts")
    val uploadedParts: kotlin.collections.List<kotlin.Int>? = null,

    /* 需要上传的分片对应的预签名URL字典（Key为分片序号，Value为PUT请求的URL） */
    @SerializedName("uploadUrls")
    val uploadUrls: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

)

