/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.response

import com.agri.pest.client.model.response.CultivationRecordDto

import com.google.gson.annotations.SerializedName

/**
 * 作物详情响应
 *
 * @param id 作物ID
 * @param plantName 植物名称
 * @param imageUrl 植物图片URL
 * @param status 植物状态
 * @param plantingDate 种植时间
 * @param maturityDate 预计成熟时间
 * @param pestCount 病虫害次数
 * @param records 种植打卡记录列表 (按 tagType 分类，Value 为按日期降序排列的记录)
 * @param createdAt 创建时间
 */


data class MyCropResponseDto (

    /* 作物ID */
    @SerializedName("id")
    val id: kotlin.Long? = null,

    /* 植物名称 */
    @SerializedName("plantName")
    val plantName: kotlin.String? = null,

    /* 植物图片URL */
    @SerializedName("imageUrl")
    val imageUrl: kotlin.String? = null,

    /* 植物状态 */
    @SerializedName("status")
    val status: kotlin.String? = null,

    /* 种植时间 */
    @SerializedName("plantingDate")
    val plantingDate: java.time.LocalDate? = null,

    /* 预计成熟时间 */
    @SerializedName("maturityDate")
    val maturityDate: java.time.LocalDate? = null,

    /* 病虫害次数 */
    @SerializedName("pestCount")
    val pestCount: kotlin.Int? = null,

    /* 种植打卡记录列表 (按 tagType 分类，Value 为按日期降序排列的记录) */
    @SerializedName("records")
    val records: kotlin.collections.Map<kotlin.String, kotlin.collections.List<CultivationRecordDto>>? = null,

    /* 创建时间 */
    @SerializedName("createdAt")
    val createdAt: java.time.OffsetDateTime? = null

)

