/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.response


import com.google.gson.annotations.SerializedName

/**
 * 帖子信息响应结果
 *
 * @param id 帖子ID
 * @param title 标题
 * @param content 内容
 * @param images 图片列表
 * @param tags 标签列表
 * @param authorId 作者ID
 * @param authorName 作者用户名
 * @param authorAvatar 作者头像
 * @param likeCount 点赞数
 * @param favoriteCount 收藏数
 * @param commentCount 评论数
 * @param isLiked 当前用户是否已点赞
 * @param isFavorited 当前用户是否已收藏
 * @param createdAt 创建时间
 * @param updatedAt 更新时间
 */


data class PostResponseDto (

    /* 帖子ID */
    @SerializedName("id")
    val id: kotlin.Long? = null,

    /* 标题 */
    @SerializedName("title")
    val title: kotlin.String? = null,

    /* 内容 */
    @SerializedName("content")
    val content: kotlin.String? = null,

    /* 图片列表 */
    @SerializedName("images")
    val images: kotlin.collections.List<kotlin.String>? = null,

    /* 标签列表 */
    @SerializedName("tags")
    val tags: kotlin.collections.List<kotlin.String>? = null,

    /* 作者ID */
    @SerializedName("authorId")
    val authorId: kotlin.Long? = null,

    /* 作者用户名 */
    @SerializedName("authorName")
    val authorName: kotlin.String? = null,

    /* 作者头像 */
    @SerializedName("authorAvatar")
    val authorAvatar: kotlin.String? = null,

    /* 点赞数 */
    @SerializedName("likeCount")
    val likeCount: kotlin.Int? = null,

    /* 收藏数 */
    @SerializedName("favoriteCount")
    val favoriteCount: kotlin.Int? = null,

    /* 评论数 */
    @SerializedName("commentCount")
    val commentCount: kotlin.Int? = null,

    /* 当前用户是否已点赞 */
    @SerializedName("isLiked")
    val isLiked: kotlin.Boolean? = null,

    /* 当前用户是否已收藏 */
    @SerializedName("isFavorited")
    val isFavorited: kotlin.Boolean? = null,

    /* 创建时间 */
    @SerializedName("createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    /* 更新时间 */
    @SerializedName("updatedAt")
    val updatedAt: java.time.OffsetDateTime? = null

)

