/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.response


import com.google.gson.annotations.SerializedName

/**
 * 服务端耗时剖析信息
 *
 * @param requestId 本次请求唯一标识
 * @param clientIp 服务端解析到的客户端 IP
 * @param requestBytes HTTP 请求体字节数（用于估算上传/传输开销）
 * @param hasImage 是否包含图片输入
 * @param imageUrlLength imageUrl 字符串长度（base64 时通常很大）
 * @param imageUrlType 图片输入类型：none/url/base64/unknown
 * @param extraInfoLength extraInfo 字符串长度（用于估算上下文注入开销）
 * @param singleModel 是否使用单模型方案（单模型：多模态直推；多模型：视觉识别+工具推导）
 * @param getUserIdMs 获取用户 ID 耗时（毫秒）
 * @param normalizeImageUrlMs 清洗与规范化 imageUrl 耗时（毫秒）
 * @param visionMs 视觉模型耗时（毫秒，仅多模型有图片时不为 0）
 * @param agentMs Agent/模型推理耗时（毫秒，含工具调用）
 * @param saveHistoryMs 保存历史记录耗时（毫秒）
 * @param totalMs 服务端总耗时（毫秒）
 */


data class Profile (

    /* 本次请求唯一标识 */
    @SerializedName("requestId")
    val requestId: kotlin.String? = null,

    /* 服务端解析到的客户端 IP */
    @SerializedName("clientIp")
    val clientIp: kotlin.String? = null,

    /* HTTP 请求体字节数（用于估算上传/传输开销） */
    @SerializedName("requestBytes")
    val requestBytes: kotlin.Long? = null,

    /* 是否包含图片输入 */
    @SerializedName("hasImage")
    val hasImage: kotlin.Boolean? = null,

    /* imageUrl 字符串长度（base64 时通常很大） */
    @SerializedName("imageUrlLength")
    val imageUrlLength: kotlin.Int? = null,

    /* 图片输入类型：none/url/base64/unknown */
    @SerializedName("imageUrlType")
    val imageUrlType: kotlin.String? = null,

    /* extraInfo 字符串长度（用于估算上下文注入开销） */
    @SerializedName("extraInfoLength")
    val extraInfoLength: kotlin.Int? = null,

    /* 是否使用单模型方案（单模型：多模态直推；多模型：视觉识别+工具推导） */
    @SerializedName("singleModel")
    val singleModel: kotlin.Boolean? = null,

    /* 获取用户 ID 耗时（毫秒） */
    @SerializedName("getUserIdMs")
    val getUserIdMs: kotlin.Long? = null,

    /* 清洗与规范化 imageUrl 耗时（毫秒） */
    @SerializedName("normalizeImageUrlMs")
    val normalizeImageUrlMs: kotlin.Long? = null,

    /* 视觉模型耗时（毫秒，仅多模型有图片时不为 0） */
    @SerializedName("visionMs")
    val visionMs: kotlin.Long? = null,

    /* Agent/模型推理耗时（毫秒，含工具调用） */
    @SerializedName("agentMs")
    val agentMs: kotlin.Long? = null,

    /* 保存历史记录耗时（毫秒） */
    @SerializedName("saveHistoryMs")
    val saveHistoryMs: kotlin.Long? = null,

    /* 服务端总耗时（毫秒） */
    @SerializedName("totalMs")
    val totalMs: kotlin.Long? = null

)

