/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.response

import com.agri.pest.client.model.response.PageResultPostResponseDto
import com.agri.pest.client.model.response.PostResponseDto

import com.google.gson.annotations.SerializedName

/**
 * 搜索结果响应，包含匹配帖子和推荐内容
 *
 * @param matches 
 * @param recommendations 推荐的相关帖子列表 (基于算法或热度)
 * @param suggestions 建议的搜索关键词列表 (纠错或扩展)
 */


data class SearchResultResponse (

    @SerializedName("matches")
    val matches: PageResultPostResponseDto? = null,

    /* 推荐的相关帖子列表 (基于算法或热度) */
    @SerializedName("recommendations")
    val recommendations: kotlin.collections.List<PostResponseDto>? = null,

    /* 建议的搜索关键词列表 (纠错或扩展) */
    @SerializedName("suggestions")
    val suggestions: kotlin.collections.List<kotlin.String>? = null

)

