/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.response


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param unsorted 
 * @param sorted 
 * @param empty 
 */


data class SortObject (

    @SerializedName("unsorted")
    val unsorted: kotlin.Boolean? = null,

    @SerializedName("sorted")
    val sorted: kotlin.Boolean? = null,

    @SerializedName("empty")
    val empty: kotlin.Boolean? = null

)

