/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model.response


import com.google.gson.annotations.SerializedName

/**
 * 标签信息
 *
 * @param name 标签名称
 * @param usageCount 引用次数
 */


data class TagDto (

    /* 标签名称 */
    @SerializedName("name")
    val name: kotlin.String? = null,

    /* 引用次数 */
    @SerializedName("usageCount")
    val usageCount: kotlin.Long? = null

)

