/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model


import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param id 
 * @param username 
 * @param phone 
 * @param role 
 * @param createdAt 
 * @param fullName 
 * @param avatarUrl 
 * @param bio 
 * @param location 
 * @param followedCrops 
 */


data class AdminUserResponseDto (

    @SerializedName("id")
    val id: kotlin.Long? = null,

    @SerializedName("username")
    val username: kotlin.String? = null,

    @SerializedName("phone")
    val phone: kotlin.String? = null,

    @SerializedName("role")
    val role: kotlin.String? = null,

    @SerializedName("createdAt")
    val createdAt: java.time.OffsetDateTime? = null,

    @SerializedName("fullName")
    val fullName: kotlin.String? = null,

    @SerializedName("avatarUrl")
    val avatarUrl: kotlin.String? = null,

    @SerializedName("bio")
    val bio: kotlin.String? = null,

    @SerializedName("location")
    val location: kotlin.String? = null,

    @SerializedName("followedCrops")
    val followedCrops: kotlin.String? = null

)

