/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.agri.pest.client.model

import com.agri.pest.client.model.PageAdminUserResponseDto

import com.google.gson.annotations.SerializedName

/**
 * 
 *
 * @param code 
 * @param message 
 * @param `data` 
 */


data class ResultPageAdminUserResponseDto (

    @SerializedName("code")
    val code: kotlin.Int? = null,

    @SerializedName("message")
    val message: kotlin.String? = null,

    @SerializedName("data")
    val `data`: PageAdminUserResponseDto? = null

)

